### ISSUE TITLE
WIKI에 기획서 정리한 것 올리기

### ISSUE THREAD

**Issue by TaehwanGo** [TEAM-ARK/sprout-front#2]
당분간 github 그대로 사용할게요

Jira, Confluence는 제가 회사에서 좀 더 익숙해지면 도입해볼게요

**Comment by hyoni0817** [comment]
[wiki](https://github.com/TEAM-ARK/sprout-front/wiki/%5B%EB%94%94%EC%9E%90%EC%9D%B8%5D%ED%94%84%EB%A1%9C%ED%86%A0%ED%83%80%EC%9E%85-%EC%84%A4%EA%B3%84)에 추가했습니다 :)
